// <auto-generated />
using System;
using ListasTarefasMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListasTarefasMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240908040244_CriandoBanco")]
    partial class CriandoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ListasTarefasMVC.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("33719da0-4eee-4177-b29f-a823f46f53a6"),
                            Nome = "Trabalho"
                        },
                        new
                        {
                            CategoriaId = new Guid("c97796bd-04cd-4b45-aa5c-e68fb1ee2eb9"),
                            Nome = "Casa"
                        },
                        new
                        {
                            CategoriaId = new Guid("65120c94-f5a0-49d0-8889-32681132f8ab"),
                            Nome = "Faculdade"
                        },
                        new
                        {
                            CategoriaId = new Guid("174a8799-0e2a-4927-a9e0-4d5e8e5959a3"),
                            Nome = "Compras"
                        },
                        new
                        {
                            CategoriaId = new Guid("42051edb-3fc4-4bdb-afc7-149df641a00d"),
                            Nome = "Academia"
                        });
                });

            modelBuilder.Entity("ListasTarefasMVC.Models.Status", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = new Guid("ce04fc07-8742-48a1-847b-9eb4091de4c4"),
                            Nome = "Aberto"
                        },
                        new
                        {
                            StatusId = new Guid("cce02a56-a182-4845-8398-40117b6c9f89"),
                            Nome = "Completo"
                        });
                });

            modelBuilder.Entity("ListasTarefasMVC.Models.Tarefa", b =>
                {
                    b.Property<Guid>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TarefaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("ListasTarefasMVC.Models.Tarefa", b =>
                {
                    b.HasOne("ListasTarefasMVC.Models.Categoria", "Catergoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListasTarefasMVC.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catergoria");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
